---
ntp_enabled: true
ntp_timezone: Etc/UTC
ntp_manage_config: true
ntp_servers:
 - 0.pool.ntp.org iburst
 - 1.pool.ntp.org iburst
 - 2.pool.ntp.org iburst
 - 3.pool.ntp.org iburst
aam_ntp_servers:
 - 172.30.6.11 iburst
 - 172.30.6.12 iburst

