---
- name: Ensure User's Group exist
  group:
    name: '{{ item.name }}'
    state: present
  with_items: '{{ ssh_users }}'

- name: Ensure wheel group exist
  group:
    name: wheel
    state: present

- name: Create user
  user: 
    name: '{{ item.name }}'
    comment: '{{ item.comment }}'
    group: '{{ item.name }}'
    groups: wheel
    append: yes
  with_items: '{{ ssh_users }}'

- name: Add ssh user keys
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: '{{ ssh_users }}' 

