---
# tasks file for iptables (CentOS specific)

- name: Install iptables packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ iptables_packages }}"
  tags:
    - iptables
