---
- name: ensure github.com is a known host
  lineinfile:
    dest: '{{ homeDir }}/.ssh/known_hosts'
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: create downloadDir
  file: path={{ downloadDir }} state=directory

### (!) Cleanup can be disabled, to preserve an already existing directory; enable ignore_errors in Download. 
- name: Cleanup downloadDir (otherwise clone will fail if already exist)
  file: path={{ downloadDir }}/{{ repoName }} state=absent
  

- name: Download the Repository
  git: repo=https://{{ gitToken }}:x-oauth-basic@{{ gitHubServer }}/{{ gitHubCompany }}/{{ repoName }}.git
       dest={{ downloadDir }}/{{ repoName }}
       accept_hostkey=true
       recursive=yes
       ## version: {{ gitTag }}
     
