---
- name: Ensure gitlab is a known host
  lineinfile:
    dest: '{{ homeDir }}/.ssh/known_hosts'
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa gitlab-int.notdevops.com') }}"
    regexp: "^gitlab\\.com"

- name: Create downloadDir
  file: path={{ downloadDir }} state=directory 

### (!) Cleanup can be disabled, to preserve an already existing directory; enable ignore_errors in Download. 
- name: Cleanup downloadDir (otherwise clone will fail if already exist)
  file: path={{ downloadDir }}/{{ repoName }} state=absent

- name: Download the Repository
  git: repo=git@{{ gitLabServer }}:{{ gitLabCompany }}/{{ repoName }}.git
       dest={{ downloadDir }}/{{ repoName }}
       recursive=yes
       ## version: {{ gitTag }}
